book/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    #path('', views.index, name='index'),
    path('', login_required(views.BookListView.as_view(), login_url='/login'), name='index'),
    # path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    re_path(r'add/$', views.book_add, name='book_add'),

    re_path(r'cart/add/(?P<slug>[\w-]+)/$', views.cart_add, name='cart_add'),
    re_path(r'cart/delete/(?P<slug>[\w-]+)/$', views.cart_delete, name='cart_delete'),
    re_path(r'cart/list/$', views.cart_list, name='cart_list'),
    re_path(r'cart/checkout/$', views.cart_checkout, name='cart_checkout'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('hello/<int:id>', views.hello, name='hello'),
    re_path(r'article/(?P<year>[0-9]{4})/(?P<slug>[\w-]+)/$', views.article, name='article'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from book.api import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
    path('book/', include(('book.urls', 'book'), namespace='book')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>{% block title %}Test Project{% endblock %}</title>
  </head>
  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Book Store</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'myapp:index' %}">Home</a>
            <a class="p-2 text-dark" href="{% url 'book:index' %}">Book</a>
        </nav>

        {% if request.session.cart_qty %}
        <a class="btn btn-secondary mx-2" href="{% url 'book:cart_list' %}"><i class="fa fa-shopping-cart"></i>  {{ request.session.cart_qty }}</a>
        {% endif %}

        {% if not user.is_authenticated %}
        <a class="btn btn-outline-primary mx-2" href="{% url 'myapp:signup' %}">Sign up</a>
        <a class="btn btn-info mx-2" href="{% url 'myapp:login' %}">Log in</a>
        {% endif %}

        {% if user.is_authenticated %}
          <span>Hello, {{ request.user.username }}</span>
          <form method="post" action="{% url 'myapp:logout' %}" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mx-2">Log out</button>
          </form>
        {% endif %}
    </div>

    <div class="container-fluid">
      {% if messages %}
        {% for msg in messages %}
          {% if msg.tags == 'success' %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Success</strong> {{ msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
        
          {% if msg.tags == 'error' %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Error</strong> {{ msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
        {% endfor %}
      {% endif %}

      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
  </body>
</html>